run:
  deadline: 5m

linters:
  enable:
    - deadcode
    - depguard
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - megacheck
    - misspell
    - scopelint
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck

linters-settings:
  lll:
    line-length: 160
